package cluster

import (
	"fmt"
	"hash/fnv"
	"sort"
	"sync"
)

const defaultVirtualNodes = 150 // virtual tokens per physical node

// Ring is a consistent hashing ring that maps keys to cache nodes.
//
// Each physical node is represented by 150 virtual tokens spread around
// a circular uint32 space (0 to 2^32-1). This ensures even key distribution
// even with only 3 nodes.
//
// Key lookup is O(log n) via binary search over the sorted token list.
// Adding or removing a node only remaps the keys in the affected arc —
// all other keys stay on their current node.
type Ring struct {
	mu           sync.RWMutex        // protects concurrent ring modifications
	tokens       map[uint32]string   // token position → nodeID
	sortedTokens []uint32            // sorted token positions for binary search
	nodeAddrs    map[string]string   // nodeID → gRPC address (e.g. "node1:9001")
	virtualNodes int                 // number of virtual tokens per node
}

// NewRing creates an empty consistent hashing ring.
func NewRing() *Ring {
	return &Ring{
		tokens:       make(map[uint32]string),
		sortedTokens: []uint32{},
		nodeAddrs:    make(map[string]string),
		virtualNodes: defaultVirtualNodes,
	}
}

// Add registers a node on the ring by placing virtualNodes tokens at
// deterministic positions around the ring.
//
// Token positions are generated by hashing "nodeID-0", "nodeID-1", ...,
// "nodeID-149" with FNV-1a. Using the index as a suffix ensures the tokens
// are spread evenly rather than clustered together.
func (r *Ring) Add(nodeID, addr string) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.nodeAddrs[nodeID] = addr

	for i := 0; i < r.virtualNodes; i++ {
		token := hashKey(fmt.Sprintf("%s-%d", nodeID, i))
		r.tokens[token] = nodeID
		r.sortedTokens = append(r.sortedTokens, token)
	}

	// Keep the token list sorted so binary search works correctly
	sort.Slice(r.sortedTokens, func(i, j int) bool {
		return r.sortedTokens[i] < r.sortedTokens[j]
	})
}

// Remove deregisters a node and all its virtual tokens from the ring.
//
// After removal, keys previously owned by this node will route to the
// next node clockwise — but the coordinator tracks node health separately
// and returns cache misses for unavailable nodes rather than rerouting.
func (r *Ring) Remove(nodeID string) {
	r.mu.Lock()
	defer r.mu.Unlock()

	delete(r.nodeAddrs, nodeID)

	// Rebuild the token list without this node's tokens.
	// We need to remove exactly the tokens that belong to nodeID.
	newSorted := r.sortedTokens[:0]
	for _, token := range r.sortedTokens {
		if r.tokens[token] == nodeID {
			delete(r.tokens, token)
		} else {
			newSorted = append(newSorted, token)
		}
	}
	r.sortedTokens = newSorted
}

// Get returns the nodeID and gRPC address responsible for the given key.
//
// Algorithm:
//  1. Hash the key to a uint32 position on the ring
//  2. Binary search for the first token >= that position (clockwise lookup)
//  3. If no token is >= the position, wrap around to the first token
//
// Returns ok=false only if the ring is empty (no nodes added).
func (r *Ring) Get(key string) (nodeID, addr string, ok bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	if len(r.sortedTokens) == 0 {
		return "", "", false
	}

	position := hashKey(key)

	// Binary search: find the first token >= position
	// sort.Search returns the smallest index i where sortedTokens[i] >= position
	idx := sort.Search(len(r.sortedTokens), func(i int) bool {
		return r.sortedTokens[i] >= position
	})

	// Wrap around: if position is beyond all tokens, use the first token
	if idx == len(r.sortedTokens) {
		idx = 0
	}

	token := r.sortedTokens[idx]
	nodeID = r.tokens[token]
	addr = r.nodeAddrs[nodeID]
	return nodeID, addr, true
}

// Nodes returns all currently registered node IDs.
// Used by the coordinator to initialise health tracking.
func (r *Ring) Nodes() []string {
	r.mu.RLock()
	defer r.mu.RUnlock()

	nodes := make([]string, 0, len(r.nodeAddrs))
	for id := range r.nodeAddrs {
		nodes = append(nodes, id)
	}
	return nodes
}

// NodeAddr returns the gRPC address for a given node ID.
func (r *Ring) NodeAddr(nodeID string) (string, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	addr, ok := r.nodeAddrs[nodeID]
	return addr, ok
}

// hashKey computes a uint32 token position for a string using FNV-1a.
//
// FNV-1a is a non-cryptographic hash chosen for:
//   - Speed: just XOR and multiply, no heavy computation
//   - Distribution: keys spread evenly across the uint32 space
//   - Determinism: same input always produces the same output
func hashKey(key string) uint32 {
	h := fnv.New32a()
	h.Write([]byte(key))
	return h.Sum32()
}
